### ISSUE TITLE
<Task> Basic art and behavior design for the first enemy character

### ISSUE THREAD

**Issue by eco9898** [UQdeco2800/2021-studio-2#15]
# **Description**
**Task:** Basic art and behavior design for the first enemy character
**Feature:** [Team 2 - Minion enemy movement](5) 
 
Create a basic sprite and various appearances for the first enemy. Decide how this enemy will move, attack, and react to the player.
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../../wikis/page1)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitLab Username) (Discord tag)

**Comment by eco9898** [comment]
@FleurN21 has created a front view of the first enemy design

**Comment by MTbir** [comment]
Complete
