### ISSUE TITLE
<Task> Trigger melee attack animation when enemy in proximity of player 

### ISSUE THREAD

**Issue by FleurN21** [UQdeco2800/2021-studio-2#156]
# **Description**
**Task:** Trigger melee attack animation when enemy in proximity of player
**Feature:** [Team 2 - Minion combat and Boss fights](96) & [Team 2 - Minion combat and Boss fights part 2](181)

Currently, the melee attack animation plays on a loop so the enemy is constantly stabbing. 

Would prefer to have attack animations triggered only when the enemy is near the player, otherwise, it should just use directional animations (where the elf is not holding a weapon) 

**Completion Deadline:** Sep. 20

# **Member**
- Fleur Nicholson (@FleurN21) Fleur#0608

**Comment by eco9898** [comment]
Will be carried over to sprint 3

**Comment by eco9898** [comment]
This can be done through the player attack system
