### ISSUE TITLE
<Task> Round off enemy health bar edges

### ISSUE THREAD

**Issue by eco9898** [UQdeco2800/2021-studio-2#173]
# **Description**
**Task:** Round off enemy health bar edges
**Feature:** [Team 2 - Minion combat and Boss fights](96) & [Team 2 - Minion combat and Boss fights part 2](181)
 
- [ ] Minions health bar should be rounded like the players

## Dependencies
- #123

**Completion Deadline:** Sep. 16

# **Member**
- Kai Barry (@BobJohnsom) BOBJohnson#5476

**Comment by eco9898** [comment]
Will be carried over to sprint 3

**Comment by eco9898** [comment]
This may be delayed to sprint 4 or entirely dropped

**Comment by MTbir** [comment]
health bar does not need to have round edge
