### ISSUE TITLE
[Task] Design 3 more levels.

### ISSUE THREAD

**Issue by GoldMan93** [UQdeco2800/2021-studio-2#198]

**Comment by BenjaminGonzalez** [comment]
New Style for a level...
![image](https://user-images.githubusercontent.com/24380726/133401146-9d5b469c-506b-471d-9952-7ca5b0d4ebed.png)

Inspo, Palace back room
Ideas, This level would have thin corridors for people to get around and then large fancy rooms

**Comment by BenjaminGonzalez** [comment]
![image](https://user-images.githubusercontent.com/24380726/133401375-4dfb7fe1-b405-45cf-8fbb-96c2f732c18b.png)

Level More flesshed out

**Comment by BenjaminGonzalez** [comment]
![image](https://user-images.githubusercontent.com/24380726/133401416-a12349a9-b82a-498d-9de6-0e2356c7caa7.png)

Added a green room to be like a courtyard like room and also test if it would look outdoors

**Comment by BenjaminGonzalez** [comment]
Entire level

![image](https://user-images.githubusercontent.com/24380726/133401536-a74d4ac1-928f-4400-b759-3d758ade0965.png)

**Comment by BenjaminGonzalez** [comment]
Boss Room

![image](https://user-images.githubusercontent.com/24380726/133401794-d48541a2-4a3b-48c0-9c32-77bf2f2b6dec.png)

**Comment by BenjaminGonzalez** [comment]
Entire Level

![image](https://user-images.githubusercontent.com/24380726/133401862-f5b2f4cb-b3b3-4e24-9877-bc4015db7d40.png)

**Comment by BenjaminGonzalez** [comment]
Final level Idea

![image](https://user-images.githubusercontent.com/24380726/133402017-d1ae8c73-c695-4ff8-b6ee-be966745e488.png)

Inspo, hell, lava island
idea, walk around on lil wooden things and kill some monsters

**Comment by BenjaminGonzalez** [comment]
Boss Room

![image](https://user-images.githubusercontent.com/24380726/133402187-a7143623-f67d-456b-aa39-ed92c72e50d3.png)

**Comment by BenjaminGonzalez** [comment]
Finished Level

![image](https://user-images.githubusercontent.com/24380726/133402253-ab049f26-3af0-490f-8e97-08e10cf3e862.png)
