### ISSUE TITLE
<Task> Improve collision with the player

### ISSUE THREAD

**Issue by eco9898** [UQdeco2800/2021-studio-2#22]
# **Description**
**Task:** Improve collision with the player
**Feature:** [Team 2 - Minion enemy movement](5) 
 
The current collision detection isn't the best and causes issues with bouncing the player off of the enemies.
 
# **Dependencies**
- #21 (Heavily tied together)

**Completion Deadline:** Aug. 26
 
# **Documentation**
- [Collision Wiki](../wikis/Physics)
 
# **Member**
- Kai Barry  (@BobJohnsom) (BOBJohnson#5476)
- Eli (@eco9898 ) (.♡.𝓮𝓵𝓲.♡.#5723) (assisting if needed)

**Comment by BobJohnsom** [comment]
Issue has been completed. The enimies have an increased knockback to prevent the enemies from clipping into the player
