### ISSUE TITLE
Integration regarding design with other teams

### ISSUE THREAD

**Issue by BenjaminGonzalez** [UQdeco2800/2021-studio-2#268]
This issue is to record contributions with design from other teams

**Comment by ameliarow** [comment]
Sprint 2 Map Assets

![bush_outline](https://user-images.githubusercontent.com/88031503/135835843-a488ad57-1011-498e-8680-fa1efa73e721.png)
![candle_nooutline](https://user-images.githubusercontent.com/88031503/135835852-f584bc68-265b-4fb6-a4f5-1b084b72eff1.png)
![candle_outline](https://user-images.githubusercontent.com/88031503/135835854-100500bf-3c21-41b5-9f94-08b187bd2edc.png)
![chair_nooutline](https://user-images.githubusercontent.com/88031503/135835856-be298704-c575-4977-b74a-a2c9f5fb1192.png)
![chair_outline](https://user-images.githubusercontent.com/88031503/135835858-a22db4ea-0f34-45bc-9fa2-0d897b43af8e.png)
![helmet_v1](https://user-images.githubusercontent.com/88031503/135835863-f1150499-5b38-4b60-86ef-55e00c39be27.png)
![helmet_v2](https://user-images.githubusercontent.com/88031503/135835865-9849648d-8eef-4102-bc3e-82757a40777a.png)
![helmet_v3](https://user-images.githubusercontent.com/88031503/135835871-2b84706b-7f70-4c2a-96aa-4a29f0b7228a.png)
![knife_nooutline](https://user-images.githubusercontent.com/88031503/135835875-aa6a13ce-d30d-43c7-a4cf-e6239c4df33a.png)
![knife_outline](https://user-images.githubusercontent.com/88031503/135835877-371e3da3-12aa-406e-a046-ed0d46fd7fa8.png)
![stonerubble_outline](https://user-images.githubusercontent.com/88031503/135835890-b873fac3-2d01-4aa4-81a2-8176fd42b58e.png)
![telpad_v1](https://user-images.githubusercontent.com/88031503/135835891-d1e44085-b4ed-4470-a20e-a21aec7635b9.png)
![torch_outline](https://user-images.githubusercontent.com/88031503/135835896-691d3e23-96a4-43a0-90b1-c8596681f2d2.png)
![woodchest_outline](https://user-images.githubusercontent.com/88031503/135835898-78ad2719-d3aa-48af-b6a1-61e6023f5778.png)
![woodchest_v1](https://user-images.githubusercontent.com/88031503/135835903-6eb5d516-a8c2-4e8d-9e88-5d809f0c6384.png)

**Comment by ameliarow** [comment]
Lava Map Tiles

![lava_v1](https://user-images.githubusercontent.com/88031503/135835878-2a75e056-6875-43b0-a85a-9aa9f4c84c33.png)
![lava_v2](https://user-images.githubusercontent.com/88031503/135835880-db4a1043-6454-483f-9df8-e7387ef58cb8.png)
![lava_v3](https://user-images.githubusercontent.com/88031503/135835881-fed9bb15-796a-46a1-91aa-04c030d64d33.png)
![redtile_v1](https://user-images.githubusercontent.com/88031503/135835883-a586c1ba-461b-45a6-9193-dcc0b0e53b1c.png)
![darkfloor_v1](https://user-images.githubusercontent.com/88031503/135835860-ed9e9bbe-4e83-4a3c-b589-5037c8b51175.png)

**Comment by ameliarow** [comment]
### Outdoor Map Assets
![brokenwood_v1](https://user-images.githubusercontent.com/88031503/135836492-1325f1f5-7c60-4048-b579-d81d77f642a8.png)
![flower_v1](https://user-images.githubusercontent.com/88031503/135836496-030b44c8-54ed-4a0a-afbc-dccf552c1b6c.png)
![flower_v2](https://user-images.githubusercontent.com/88031503/135836497-143c1aa8-bda5-4b6d-8d6b-d018e2e11797.png)
![flower_v3](https://user-images.githubusercontent.com/88031503/135836500-6b26e8b6-3dfd-46d7-a963-e3d6eada6853.png)
![shrub_v2](https://user-images.githubusercontent.com/88031503/135836503-64035a1e-2476-42dc-b50f-340dd0370f93.png)
![barrow_v1](https://user-images.githubusercontent.com/88031503/135836525-bf8f7dc3-78be-4968-aad7-3a7d1556c508.png)
![fence_v2](https://user-images.githubusercontent.com/88031503/135836531-0071642e-f420-464a-90b7-f8e16d937731.png)
![fenceup_v1](https://user-images.githubusercontent.com/88031503/135836634-761a5611-a1fb-4d63-af8a-911230e9d9ab.png)
![firesticks_v1](https://user-images.githubusercontent.com/88031503/135836535-4e5a03c3-2a02-44a3-9ac0-fa2bd0614ddb.png)
![grassystone_v1](https://user-images.githubusercontent.com/88031503/135836538-e3079602-a908-4bb7-a328-3e2111ff8dcf.png)
![log_v2](https://user-images.githubusercontent.com/88031503/135836539-badfa49b-f572-4a27-a6ea-ba69a0f9b73b.png)
![pinetree_v1](https://user-images.githubusercontent.com/88031503/135836542-cb2e4e99-590c-49e4-9eac-55a178ade3ae.png)
![shrub_v1](https://user-images.githubusercontent.com/88031503/135836543-f5749cfe-5701-49ec-bbd4-3bf64331b1b5.png)

**Comment by ameliarow** [comment]
### Outdoor Map Tiles

![grasspatch_v1](https://user-images.githubusercontent.com/88031503/135836501-0d6e25bd-1add-4f07-b768-64dd5d65409b.png)
![dirt_v1](https://user-images.githubusercontent.com/88031503/135836528-1b7e5676-8745-4272-8dea-8d5845df4423.png)
![dirtfloor_v1](https://user-images.githubusercontent.com/88031503/135836529-8fd433e8-93c9-4406-a3f5-9a77c29690c0.png)
![stonefloor_v1](https://user-images.githubusercontent.com/88031503/135836544-09b2ee51-dae2-4efe-93cc-5c34d02a1f17.png)
![stonefloor_v2](https://user-images.githubusercontent.com/88031503/135836548-dfadcb17-359e-430d-866c-64a4f0cbf821.png)
![stonefloor_v3](https://user-images.githubusercontent.com/88031503/135836550-5ae8bcd8-2dc8-45ee-96ee-e7e511a2bbda.png)
