### ISSUE TITLE
<Task> entre door concept design and animation

### ISSUE THREAD

**Issue by GoldMan93** [UQdeco2800/2021-studio-2#62]
- [x] door concept design
- [x] pixel door art
- [x] door animation
- [ ] implement in game engine TBD

**Comment by GoldMan93** [comment]
![door_v0 1](https://user-images.githubusercontent.com/88018771/130590593-d761dff0-ab73-46ac-8a82-e35c0458a36f.png)
Basic room entre design

**Comment by othiem** [comment]
![door_open](https://user-images.githubusercontent.com/88184771/131454561-2cf4ec51-e51f-489f-8273-33f534fd2ada.gif)
Door open

**Comment by GoldMan93** [comment]
the door is replaced by teleport #134
