### ISSUE TITLE
<Task> spike art

### ISSUE THREAD

**Issue by GoldMan93** [UQdeco2800/2021-studio-2#66]
- [x] spike wall 

- [x]  spike door

**Comment by othiem** [comment]
Spike Wall
![New Piskel-2](https://user-images.githubusercontent.com/88184771/131256111-98fd2b80-41eb-4734-9639-12544f05f3d6.png)

**Comment by othiem** [comment]
Spike Door
![New Piskel](https://user-images.githubusercontent.com/88184771/131256135-f4a4b04a-0e99-49b2-8f1b-1c2b8f3a289a.gif)
