### ISSUE TITLE
[Feature] Team 4 - Level Design 

### ISSUE THREAD

**Issue by BenjaminGonzalez** [UQdeco2800/2021-studio-2#87]
# Description 
Evolve current map rendering to be more game-like. This will involve making larger rooms, and connecting these rooms, to make a larger level. This larger level will have initial rooms and a boss room(s).

There will be more complexity and fun things to interact with via traps and making the game more immersive via determining a good camera height.

# New Milestones
## Map Design
- [x] Initial rough design of a full, larger level
- [x] Design Larger Map in Tiled
- [x] More tiles designs for tileset
- [x] Better Trap Design
- [x] Wall Blocking Textures

## Objects (traps) Creation
- [ ] Create trap that teleports Player (after walking over and interacting)
- [x] #155

## Map Rendering
- [x] Programmatic rendering of walls
- [x] Determine appropriate zoom level

# Dependancies
Tiled Map requires the initial design of the level
Tiled Map requires better tile designs

# Documentation
[Wiki](https://github.com/UQdeco2800/2021-studio-2/wiki)

# Members
Benjamin Gonzalez (@BenjaminGonzalez) (Benjamin-Gonzalez-#2927)
Sicheng Pan (@GoldMan93) (GW.Goldman#8858)
William Parker (@parker334) (parker334#2323)
Nicolas Armstrong (@Nicolas-Armstrong) (FalconLuma#3614)
Quan Tran (@othiem) (Quan Tran#0165)

**Comment by othiem** [comment]
Spike Wall:
![Spike Wall1](https://user-images.githubusercontent.com/88184771/131952136-27b72772-2189-4717-9c7a-3bcfda1f8765.png)
![Spike Wall 2](https://user-images.githubusercontent.com/88184771/131952139-a0a0c8c5-5708-4f90-8fab-a4bc226bae0b.png)
![Spike Wall 3](https://user-images.githubusercontent.com/88184771/131952159-c5353bc0-5d0c-4c50-a2fc-bf5f18bc0058.png)

**Comment by othiem** [comment]
![Table 1](https://user-images.githubusercontent.com/88184771/132997966-1abf9f1f-4b32-4dce-a884-1821a3bfb131.png)
![Chair](https://user-images.githubusercontent.com/88184771/132997975-87f4f38b-10e8-4db5-ab63-89b04032d8fc.png)
![Table 2](https://piskel-imgstore-b.appspot.com/img/93fa4c9e-13dd-11ec-a8fa-cb1775e2a42e.gif)

**Comment by othiem** [comment]
![fallen-pillar2](https://user-images.githubusercontent.com/88184771/132998089-20f179f8-c49e-4787-9dfd-7372df1e6091.png)
![fallen-pillar1](https://user-images.githubusercontent.com/88184771/132998091-77743c2a-6dea-49eb-a4f1-22ca0f250ff9.png)
