### ISSUE TITLE
<Task> More variety in Tile set.

### ISSUE THREAD

**Issue by BenjaminGonzalez** [UQdeco2800/2021-studio-2#94]
Add Movement blocking tiles

- [x] Fallen Pillar
- [x] Floor Traps (lava)
- [x] More

**Comment by othiem** [comment]
![lava](https://user-images.githubusercontent.com/88184771/132285719-bc854194-f583-4029-b5f8-51641999d1ac.png)

**Comment by othiem** [comment]
![lava2](https://user-images.githubusercontent.com/88184771/132288009-a641717f-6b74-4f4c-a691-c9728084e21e.png)

**Comment by othiem** [comment]
More:

Stairs 64x64
![Stairs2](https://user-images.githubusercontent.com/88184771/132288159-76c05887-9b94-4937-8c50-2bd911e112d3.png)

Wood Floor 64x64
![wood-floor](https://user-images.githubusercontent.com/88184771/132288201-1e10c74e-4340-458c-9483-3a375b46d142.png)

Rock Floor 64x64
![rock-floor](https://user-images.githubusercontent.com/88184771/132288203-fba034a2-b623-467b-a8f7-6f7d6f0d1ac1.png)

**Comment by othiem** [comment]
Fallen Pillar
![fallen-pillar1](https://user-images.githubusercontent.com/88184771/132292206-ff257d60-0bd8-4451-a93d-f631e4d89a36.png)

![fallen-pillar2](https://user-images.githubusercontent.com/88184771/132292218-6507f103-9afc-479e-bc71-217870d1c43e.png)

**Comment by BenjaminGonzalez** [comment]
Added many new designs including new walls, floor textures, rotations of the lava, fixed the roof tiles to suit all situations and added variation to existing tiles as seen in the below tileset

![unnamed (4)](https://user-images.githubusercontent.com/24380726/132974498-0d44f0ca-e3d4-4413-a2b4-c0797330c707.png)
